// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    res.locals = {
      title: 'Try LightSide',
      header: 'Try LightSide'
    };
    return res.render('index');
  };

  exports.results = function(req, res) {
    res.locals = {
      title: 'Try LightSide',
      header: 'Results'
    };
    return res.render('results');
  };

  exports.csvPage = function(req, res) {
    res.locals = {
      title: 'Try LightSide',
      header: 'CSV Upload Page'
    };
    return res.render('csvPage');
  };

}).call(this);

//# sourceMappingURL=index.map
