// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    res.locals = {
      title: 'This is the Title',
      header: 'LightSide Main Page'
    };
    return res.render('index');
  };

}).call(this);

//# sourceMappingURL=index.map
