// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    res.locals = {
      title: 'LightSide',
      header: 'LightSide Main Page'
    };
    return res.render('index');
  };


  /*exports.results = (req, res) ->
    res.locals = {
      title: 'LightSide',
      header: 'LightSide Results Page'
    }
    res.render 'results'
  
  exports.csvPage = (req, res) ->
    res.locals = {
      title: 'LightSide',
      header: 'LightSide CSV Upload Page'
    }
    res.render 'csvPage'
   */

}).call(this);

//# sourceMappingURL=index.map
