// Generated by CoffeeScript 1.7.1
(function() {
  var requestLightSide;

  requestLightSide = require('request');

  exports.postAnswer = function(request, response, answer) {
    var options;
    options = {
      'url': 'https://try-api.lightsidelabs.com/api/',
      method: 'get',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Token '
      }
    };
    return requestLightSide(options, function(error, response, body) {
      return console.log('made request');
    });
  };

}).call(this);
